### ISSUE TITLE
GitHub Actions fails Maven Build 

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Maven-Using-CMD#11]
GitHub Actions for this repository is completed by @navyakanu at #10 
But it goes in a long unusual build and keeps failing.
Check for possible changes in yml file to optimize and get it up and working.

**Comment by navyakanu** [comment]
@NishkarshRaj , will take a look at it, looks like its some permission issue for the failure, trying to figure out which file needs permission
For the long running build, i guess i am installing java in the ubuntu machine, not sure if thats causing the issue, will try to fix them

**Comment by NishkarshRaj** [comment]
Thanks @navyakanu 
Solved and closing the issue 💯
