### ISSUE TITLE
Jenkins automation

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Maven-Using-CMD#5]
Create a script to trigger Jenkins automation tasks whenever a file is pushed into the source repository.

**Comment by navyakanu** [comment]
@NishkarshRaj, I would like to pick up this issue, could you please elaborate? Does this mean trigger build/deploy pipeline whenever a code is pushed to this repository?
Is it okay if we achieve this using github actions? or any other CI then jenkins?

**Comment by NishkarshRaj** [comment]
@navyakanu Thank you for reaching out and showing interest on this repository.

Yes, I want an automated pipeline via script or any other means to generate build of the master branch code base whenever a new change is merged with it.

Sure, we can work on GitHub Actions or any other CI like Travis etc, if you want.

**Comment by acodebreaker** [comment]
please assign this to me

**Comment by NishkarshRaj** [comment]
@acodebreaker sorry brother, its already done! I forgot to close the issue. 👍
