### ISSUE TITLE
JUnit Integration with Maven

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Maven-Using-CMD#6]
Create a JUnit test case which checks for the presence of words "Hello" and "World" in the source Java file

**Comment by RiyaJohn** [comment]
Raised PR, please review https://github.com/NishkarshRaj/Maven-Using-CMD/pull/8

**Comment by NishkarshRaj** [comment]
Thanks @RiyaJohn for solving this issue 😄
